nucypher/taco-web

- CHANGELOG.md
- package.json
- src/agents/policy-manager.ts
- src/characters/alice.ts
- src/characters/bob.ts
- src/characters/enrico.ts
- src/characters/porter.ts
- src/crypto/constants.ts
- src/crypto/keyring.ts
- src/crypto/powers.ts
- src/kits/message.ts
- src/kits/retrieval.ts
- src/policies/collections.ts
- src/policies/policy.ts
- src/versioning.ts
- test/acceptance/alice-grants.test.ts
- test/integration/enrico.test.ts
- test/integration/message-kit.test.ts
- test/integration/pre.test.ts
- test/unit/serialize.test.ts
- test/unit/signature.test.ts
- test/utils.ts
- tsconfig.json
> nucypher-core update

- src/characters/alice.ts
- src/policies/policy.ts
- test/acceptance/alice-grants.test.ts
- test/acceptance/delay-enact.ts
- test/utils.ts
> Enact policies with a different publisher

- src/agents/contracts.ts
- src/characters/alice.ts
- src/characters/bob.ts
- src/config.ts
- src/index.ts
- src/types.ts
- test/utils.ts
> Polygon mainnet config

- src/characters/tDec.ts
- test/acceptance/alice-grants.test.ts
- test/integration/tdec.test.ts
- test/utils.ts
Tests currently don't pass.
I'm not sure of the best way to test this. Ideally I'd like to have a full integration test (all the internal components already have unit tests) - but that requires a connection to a test network or a locally running network (with all the smart contracts deployed)
Otherwise we can try and mock some stuff out, but because this is so high level I've struggled. @piotr-roslaniec @KPrasch any help greatly appreciated
> Add builder function for dynamic tDec configurations

- package.json
- src/characters/enrico.ts
- src/characters/porter.ts
- src/core.ts
- src/index.ts
- src/kits/message.ts
- src/policies/conditions.ts
- test/integration/conditions.test.ts
- test/integration/enrico.test.ts
- test/integration/pre.test.ts
- yarn.lock
* conditions serialized and deserialized
* messagekits readable by latest python code
* Tests pass
* ReencryptionRequest integration in progress
> Python compatible conditions authoring and integration

- src/index.ts
- src/policies/conditions.ts
- test/integration/conditions.test.ts
- I still have some stuff to cover, but first I want to refactor how `ConditionSet` is built. So I'm putting this PR to review now before it grows too complex.
- Used in: https://github.com/nucypher/nucypher-ts-demo-tdec/pull/2
> Expose dictionary types in conditions

- .github/workflows/main.yml
- package.json
- yarn.lock
https://github.com/skypackjs/package-check
> Improve package.json as defined by package-check

- src/policies/conditions.ts
- test/integration/conditions.test.ts
- test/utils.ts
Fixes https://github.com/nucypher/nucypher-ts/issues/103
> Chain Name -> Chain ID

- CONTRIBUTING.md
- README.md
> Update readme to match gitbook

- src/agents/subscription-manager.ts
- src/characters/alice.ts
- src/policies/conditions.ts
- src/policies/policy.ts
- src/web3.ts
- test/integration/conditions.test.ts
- Fixes: https://github.com/nucypher/nucypher-ts/issues/130
- This is a breaking change in the API, so we'd best wait for a `MAJOR` release and update all relevant examples, docs, etc.
> Replace `Web3Provider` with direct usage of `ethers.provider.Web3Provider`

- src/policies/conditions.ts
- test/integration/conditions.test.ts
- Closes #173
- Includes a small refactor of tests methods
> Add support for user-defined params in `ConditionContext`

- src/agents/contracts.ts
- src/conditions/conditions.ts
- src/conditions/providers.ts
- src/config.ts
- src/types.ts
> Integrate remaining items from SDK feedback

- README.md
> How many reviews does the PR author need?
- Adds an explainer of convention used in `nucypher-ts` package tagging
> - Fixes #...
- We have no docs for this convention, and this may be confusing for our users
> What should reviewers focus on? 
> Add testnet info to README.md

- .github/workflows/lynx.yml
- examples/taco/nodejs/src/index.ts
> How many reviews does the PR author need?
Creates a GH action that runs the node-js example on Lynx
* Action is triggered by pushing PRs, manually, and every 20 minutes.
* It will give us valuable information about state of Lynx testnet and API stability
Sister PR for Python API: https://github.com/nucypher/nucypher/pull/3274
Improvements for later:
* The 20 minutes schedule can be reconsidered soon, once we gain a bit of confidence in both Lynx and the GH action workflow.
* The workflow can be improved with more informative diagnosis in case of failures
* For the moment, it uses many hard-coded values (ritual ID, encryptor signing key, RPC provider, etc). There's lot of room for improvement there too.
> Taco Node-js Demo as GH Action

- .npmrc
- packages/shared/package.json
- packages/taco/package.json
- pnpm-lock.yaml
- vitest.config.ts
- Other
- 1
- `@nucypher/taco:0.1.0-rc.2` confirmed to work with local demo
> Release `@nucypher/taco`

- packages/taco/src/conditions/context/context.ts
- packages/taco/src/index.ts
- packages/taco/src/taco.ts
- packages/taco/src/tdec.ts
> Expose custom context params in TACo API

- packages/shared/package.json
- packages/taco/package.json
- pnpm-lock.yaml
> Release `@nucypher/taco:0.1.0-rc.3`

- demos/taco-demo/README.md
- demos/taco-nft-demo/README.md
> Add links to StackBlitz for demos

- demos/README.md
- demos/taco-demo/package.json
- demos/taco-demo/src/App.tsx
- demos/taco-demo/src/config.ts
- demos/taco-nft-demo/package.json
- demos/taco-nft-demo/src/App.tsx
- demos/taco-nft-demo/src/config.ts
- packages/pre/src/index.ts
- packages/pre/test/acceptance/delay-enact.test.ts
- packages/shared/src/contracts/agents/coordinator.ts
- packages/taco/src/conditions/condition-expr.ts
- packages/taco/src/dkg.ts
- packages/taco/src/index.ts
- packages/taco/src/taco.ts
- packages/taco/src/tdec.ts
- packages/taco/test/conditions/conditions.test.ts
- packages/taco/test/conditions/context.test.ts
- pnpm-lock.yaml
- Other
- 1
- Updates demo config (`lynx`, ritual 3)
- Fixes a bunch of chores
> Update demo config

- packages/shared/src/utils.ts
- packages/taco/test/conditions/context.test.ts
- Bugfix
- 1
> - Fixes #...
> What should reviewers focus on?
> Encode bytes in `Context` params to hex

- packages/shared/package.json
- pnpm-lock.yaml
> update @nucypher/nucypher-contracts to v0.9.0

- packages/taco/src/taco.ts
- Documentation
- 1 
- Adds JSDoc docs to methods exposed from `taco` package
> Document exposed `taco` API methods

- demos/taco-demo/package.json
- demos/taco-nft-demo/package.json
- pnpm-lock.yaml
> Fix demos on Stackblitz

- CONTRIBUTING.md
- README.md
- demos/taco-demo/README.md
- demos/taco-nft-demo/README.md
- examples/pre/webpack-5/src/index.html
- examples/taco/webpack-5/src/index.html
- packages/pre/README.md
- packages/pre/package.json
- packages/shared/README.md
- packages/shared/package.json
- packages/taco/README.md
- packages/taco/package.json
- packages/test-utils/README.md
- packages/test-utils/package.json
- pnpm-lock.yaml
- typedoc.json
- Other
- 1
- Fixes #387
**Notes**
- Please also review [this GitBook change request](https://app.gitbook.com/o/R2meumXNNad4y1B10iL7/s/WosjlL4zUGUMlcMfuSAp/~/changes/313/app-development/threshold-access-control-tac/advanced-usage/proxy-re-encryption#documentation-and-examples)
> Rename repository to `taco-web`

- demos/taco-demo/webpack.config.js
- demos/taco-nft-demo/webpack.config.js
- Other
- 1
- This is a workaround rather than a proper fix
- I just noticed this issue after #379 was fixed, but it cannot be explained by those changes
> Plug the issue with webpack not refreshing the React app in demos

- packages/shared/src/web3.ts
- packages/taco/src/conditions/const.ts
- packages/taco/test/conditions/conditions.test.ts
Add Sepolia network to supported chains by conditions.
> Add Sepolia to condition's supported chains

- demos/taco-demo/webpack.config.js
- demos/taco-nft-demo/webpack.config.js
- examples/taco/nodejs/src/index.ts
- packages/taco/src/conditions/base/shared.ts
- packages/taco/src/conditions/const.ts
- packages/taco/src/conditions/context/context.ts
- Bugfix
- 1
**Related to:**
https://github.com/nucypher/taco-web/pull/404
Move CONTEXT_PARAM_PREFIX to const.ts to fix import problem
> fix: ConditionContext import error

- packages/shared/package.json
- pnpm-lock.yaml
> chore(deps): bump nucypher-contracts version to 0.13.0

- README.md
- demos/taco-demo/README.md
- demos/taco-nft-demo/README.md
- examples/taco/nextjs/README.md
- examples/taco/nodejs/README.md
- examples/taco/react/README.md
- examples/taco/webpack-5/README.md
- packages/taco/README.md
- Other
- 1
- Refers to https://github.com/nucypher/tdec/issues/139
- Based on feedback from the Devconnect hackathon
> chore(readme): update project readmes with dev docs links

- packages/shared/package.json
- packages/shared/src/contracts/ethers-typechain/Coordinator.ts
- packages/shared/src/contracts/ethers-typechain/GlobalAllowList.ts
- packages/shared/src/contracts/ethers-typechain/factories/Coordinator__factory.ts
- packages/shared/src/contracts/ethers-typechain/factories/GlobalAllowList__factory.ts
- packages/taco/package.json
- pnpm-lock.yaml
> Publish `taco` RC

- packages/taco/README.md
> Document supported `taco` versions

- .github/workflows/tapir.yml
- demos/taco-demo/README.md
- demos/taco-demo/src/App.tsx
- demos/taco-demo/src/ConditionBuilder.tsx
- demos/taco-demo/src/index.tsx
- demos/taco-nft-demo/README.md
- demos/taco-nft-demo/src/App.tsx
- demos/taco-nft-demo/src/index.tsx
- examples/pre/nextjs/src/app/page.tsx
- examples/pre/nodejs/src/index.ts
- examples/pre/react/src/App.tsx
- examples/pre/webpack-5/src/index.ts
- examples/taco/nextjs/src/app/page.tsx
- examples/taco/nodejs/.env.example
- examples/taco/nodejs/README.md
- examples/taco/nodejs/src/index.ts
- examples/taco/react/src/App.tsx
- examples/taco/webpack-5/src/index.ts
- packages/shared/package.json
- packages/shared/src/web3.ts
- packages/taco/src/conditions/const.ts
- packages/taco/test/conditions/base/condition.test.ts
- pnpm-lock.yaml
- Feature
-  1
- Fixes #506
- Mainnet job is failing for an unrelated reason (expired ritual)
> Deprecate Mumbai on `tapir`

- packages/taco/src/conditions/context/providers.ts
- Feature
- 2
> - Fixes #...
- Fast-tracks EIP712 deprecation as per upcoming auth changes: https://github.com/nucypher/taco-web/pull/532
- Allows for a shorter deprecation window if merged before next release
> Fast-track  EIP712 deprecation

- .github/workflows/mainnet.yml
- examples/taco/nodejs/src/index.ts
- Other
- 1
- Fixes bad RPC URL causing `mainnet` job to fail
- Adds a check for `isAuthorized` method in nodejs example
> - Fixes #...
- Tested locally
- The example action will only run on `main`, so we won't see it in GH Actions until we merge
> Update `mainnet` example

- demos/taco-demo/package.json
- demos/taco-nft-demo/package.json
- examples/taco/nodejs/src/index.ts
- packages/taco/package.json
- pnpm-lock.yaml
- Other
- 1
> - Fixes #...
- How do we communicate the EIP712 deprecation to `taco` users?
> Release `@nucypher/taco:0.3.0`

- packages/taco/package.json
- packages/taco/src/conditions/base/json-api.ts
- packages/taco/src/conditions/condition-factory.ts
- packages/taco/test/conditions/base/json-api.test.ts
- packages/taco/test/conditions/base/json.test.ts
- packages/taco/test/conditions/condition-expr.test.ts
- packages/taco/test/test-utils.ts
- pnpm-lock.yaml
Merge already existing `epic-offchain` work into epic for next version of `taco`.
> - Fixes #...
> Merge `epic-offchain`

- README.md
- demos/taco-demo/README.md
- demos/taco-demo/src/App.tsx
- demos/taco-nft-demo/README.md
- demos/taco-nft-demo/src/App.tsx
- examples/taco/nextjs/README.md
- examples/taco/nodejs/README.md
- examples/taco/react/README.md
- examples/taco/webpack-5/README.md
- packages/taco/README.md
> Update links to docs.taco.build

- packages/taco/package.json
- packages/taco/schema-docs/condition-schemas.md
- packages/taco/src/conditions/schemas/context.ts
- packages/taco/src/conditions/schemas/contract.ts
- packages/taco/src/conditions/schemas/return-value-test.ts
- packages/taco/src/conditions/schemas/rpc.ts
- packages/taco/src/conditions/shared.ts
- packages/taco/test/conditions/condition-expr.test.ts
- packages/taco/test/conditions/context.test.ts
- packages/taco/test/test-utils.ts
- pnpm-lock.yaml
> Use more restrictive schemas for evm base types
