src/policies/hrac.ts, src/utils.ts
When `Alice` grants a policy, she takes in a `label` directly from the user which is in utf-8 encoding. This `label` attribute undergoes no other transformations as it is passed through `Alice.createPolicy` or the constructor of `BlockchainPolicy` where it is passed to `HRAC.derive`. 
`HRAC.derive` assumes that the label is hex encoded which it is not. My proposed solution is for `HRAC` to assume utf-8 encoding but alternate solutions would be for `Alice` or `BlockchainPolicy` to change the encoding of `label` to hex.
=> Use proper string encoding when deriving policyId

src/characters/tDec.ts, src/characters/universal-bob.ts, test/integration/tdec.test.ts
When building tDec entities dynamically, the corresponding json configuration will be returned in addition to the constructed objects.
This json can be saved and used to rebuild those entities in the future.
Fixes https://github.com/nucypher/tdec/issues/41
=> Add ability to rebuild dynamic tDec entities from static json

CHANGELOG.md, package.json, src/characters/bob.ts, src/characters/porter.ts, src/characters/universal-bob.ts, src/index.ts, src/kits/message.ts, src/kits/retrieval.ts, src/policies/conditions.ts, test/utils.ts
- Adds error handling for Porter-related decryption failures
- `Bob.retrieveAndDecrypt` will throw a verbose error
- `Bob.retrieve` and `Bob.decrypt` offer a different workflow that enables custom error handling without throwing errors
=> Error handling

CHANGELOG.md, package.json, src/policies/conditions.ts, test/integration/conditions.test.ts, test/integration/enrico.test.ts, test/integration/pre.test.ts
- `Condition.validate` method returns `{ error, ... }`, where `error` is an error type defined by `joi` 
- You can see an example of handling this `error` type [here](https://github.com/nucypher/nucypher-ts-demo-tdec/pull/9/files#diff-00accb80b3a014b9caba1977b32ca14a907ed6749856c2aba5d96e71c0301b3cR241-R246)
=> Update schema validation & error handling

examples/react-craco/src/App.js, examples/react-webpack-5-experiments/src/App.tsx, examples/webpack-5-experiments/index.js, examples/webpack-bundler/index.js, src/config.ts, src/policies/conditions.ts, test/integration/conditions.test.ts, test/integration/enrico.test.ts, test/integration/pre.test.ts, test/unit/strategy.test.ts
=> Remove default chain id and references to ibex

README.md
- For convenience, see this [preview](https://github.com/piotr-roslaniec/nucypher-ts/blob/66bbcdbcbdc5d9e10a4bd59680e5fa2220908118/README.md)
- I understand this change makes `README.md` pretty bare, but I want to avoid having to keep track of two copies the same content
=> Replace tutorial with a reference to Threshold Network's docs

.github/workflows/main.yml, CHANGELOG.md, examples/api-example.ts, examples/react-craco/package.json, examples/react-craco/src/App.js, examples/react-craco/yarn.lock, examples/react-webpack-5-experiments/package.json, examples/react-webpack-5-experiments/src/App.tsx, examples/react-webpack-5-experiments/yarn.lock, examples/webpack-5-experiments/index.js, examples/webpack-5-experiments/package.json, examples/webpack-5-experiments/yarn.lock, examples/webpack-bundler/index.js, examples/webpack-bundler/package.json, examples/webpack-bundler/yarn.lock, package.json, scripts/build-examples.bash, src/characters/alice.ts, src/policies/conditions.ts, src/web3.ts, test/acceptance/alice-grants.test.ts, test/integration/conditions.test.ts, yarn.lock
-  Update examples after v0.9.0 release
=> Release 0.9.0

test/docs/cbd.test.ts, test/utils.ts
Documentation tests are intended for early detection of modifications on nucypher-ts that involve changes on the code examples in docs.
=> Add documentation tests

src/characters/universal-bob.ts, src/policies/conditions.ts, test/integration/conditions.test.ts, test/unit/strategy.test.ts
When calling `tDecDecrypter.retrieveAndDecrypt()` the current api takes in `messageKits` and `conditionContext`. The problem with this is that `messageKits` already contains `condition`(s) and there is no guarantee that `conditionContext` contains the same condition set.
What I think the real intent here is to check if any of the `condition`(s) include a `:userAddress` and therefore require a signature. This can be done just by passing a provider to this method.
This is a proposal of how this could be accomplished, but a more thorough rework of `ConditionContext` may be warranted to be cleaner
=> refactor!: Pass provider to retireveAndDecrypt instead of ConditionContext

src/conditions/base/condition.ts, test/unit/conditions/base/condition.test.ts, test/unit/conditions/base/evm.test.ts, test/unit/conditions/base/rpc.test.ts, test/unit/conditions/base/timelock.test.ts
- Feature
- 1
- Adds `_class` field to serialized `Condition` objects to indicate condition child class
- Refers to #214
- Serialized conditions are not easily distinguishable
- This change allows for easier `Condition as MyCondition` casting
- This is a draft of one possible design to provide type casting to `Condition` consumers
=> Add class metadata to serialized conditions

package.json, src/characters/cbd-recipient.ts, src/characters/enrico.ts, src/dkg.ts, test/unit/cbd-strategy.test.ts, test/utils.ts, yarn.lock
- Feature
- 1
**What it does**
- Bump `nucypher-core` version
- Replaces dependency on `ferveo-wasm` with re-exported bindings in `nucypher-core`
**Note for reviewers**
- Not much to review here, I'm making this PR primarily to document this change
=> Update `nucypher-core` to 0.9.0

src/characters/cbd-recipient.ts, src/characters/pre-recipient.ts, src/dkg.ts, src/policies/policy.ts, src/sdk/strategy/cbd-strategy.ts, src/sdk/strategy/pre-strategy.ts, test/acceptance/alice-grants.test.ts, test/acceptance/delay-enact.test.ts, test/docs/cbd.test.ts, test/unit/cbd-strategy.test.ts, test/unit/pre-strategy.test.ts, test/utils.ts
- Feature
- 2
- Adds immutability to `*Strategy` fields
- Adds a new convenience method for creating an encrypted for a given `ConditionSet`
- #125
- Avoiding mutating objects and coupling strategy with encrypter
- Please see the original issue first: #125 
- If we want to avoid the coupling between a strategy and a condition set completely, we should replace `strategy.encrypter` with a factory method (`makeEncrypter`) completely. I.e. remove `strategy.encrypter` field.
=> Add a convenience method for creating encrypters #125

src/conditions/base/contract.ts, test/unit/conditions/base/contract.test.ts, test/unit/testVariables.ts
- Feature
-  1
- Uses `ethers` to validate `functionABI`
> - Fixes #...
- We've implemented somewhat basic validation for `functionABI`, but it's still possible to pass mangled/illegal JSON ABI into your conditions
- I need some input on this - It looks like there is going to be some overlap between `Joi` and `ethers`, and we have to implement some checks and balances ourselves on top of that.
=> Validate `functionAbi` using `ethers` ABI parser

CHANGELOG.md, package.json, src/characters/porter.ts, src/characters/pre-recipient.ts, test/utils.ts
- Bugfix
- 2
- Fixes a bug where conditions would be incorrectly deserialized from their string format, leading to `ConditionContext` attempting to access `undefined` fields 
- Changes how `ConditionContext` is prepared for Porter to fix this issue passing silently in tests
- Need to back-port this to `alpha` tree
=> Fix incorrect `Condition` parsing

.github/workflows/main.yml, package.json, yarn.lock
- Other
- 1
- Replaces `arthak-saxena/JSBundleSize@3.0.0` with `bundlemon`. The former didn't offer bundle size history tracking and generated a lot of GH comments.
=> chore(ci): use bundlemon to monitor bundle size

package.json, src/characters/cbd-recipient.ts, src/characters/enrico.ts, src/conditions/condition-expr.ts, src/conditions/condition.ts, src/conditions/context/context.ts, test/integration/dkg-client.test.ts, test/unit/cbd-strategy.test.ts, test/unit/conditions/condition-expr.test.ts, test/unit/conditions/context.test.ts, test/utils.ts, yarn.lock
- Other
- 2
- Fixes PR comments from #273 
- Closes #269 
- Closes https://github.com/nucypher/nucypher-ts/issues/293
=> Apply PR suggestions for #273

abi/Coordinator.json, src/agents/coordinator.ts, src/characters/cbd-recipient.ts, src/conditions/context/context.ts, src/dkg.ts, src/sdk/strategy/cbd-strategy.ts, src/taco.ts, test/unit/cbd-strategy.test.ts, test/unit/conditions/condition-expr.test.ts, test/unit/conditions/context.test.ts, test/unit/taco.test.ts, test/utils.ts
- Feature
- 3
- Implements a simplified API version for TACo
- Fixes #166 
- Rebased over https://github.com/nucypher/nucypher-ts/pull/286
- Please see `test/unit/taco.test.ts` for usage examples
=> Implement the TACo API module

packages/shared/src/porter.ts, packages/taco/src/conditions/context/providers.ts, packages/taco/src/tdec.ts, packages/taco/test/taco.test.ts, packages/test-utils/src/utils.ts
**DO NOT MERGE** until associated Porter PR (https://github.com/nucypher/nucypher-porter/pull/43) is merged and running on `lynx`/`tapir` testnets.
> How many reviews does the PR author need?
- Update use of Porter's `/cbd_decrypt` endpoint to ~~`/taco_decrypt`~~ `/decrypt`.
- Update all other CBD elements to use TACo.
Related to https://github.com/nucypher/nucypher-porter/pull/43
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from …
=> Update CBD elements to TACo including Porter endpoint

CONTRIBUTING.md, README.md, demos/README.md, demos/taco-demo/README.md, demos/taco-demo/package.json, demos/taco-nft-demo/README.md, demos/taco-nft-demo/package.json, examples/README.md, package.json, pnpm-lock.yaml, tsconfig.prod.json
- Other
- 1
- Fixes #307 
- Refers to #308
> What should reviewers focus on?
=> Release chores

packages/taco/src/conditions/condition-expr.ts, packages/taco/src/conditions/condition.ts, packages/taco/src/conditions/context/context.ts, packages/taco/test/conditions/condition-expr.test.ts, packages/taco/test/conditions/conditions.test.ts, packages/taco/test/conditions/context.test.ts
- Bugfix
- 2
- Adds a recursive search for custom context parameters in `CompoundCondition`
- Adds validation for unknown custom context parameters
- Refactors have conditions are passed to context (internal change)
- Based on https://github.com/nucypher/nucypher-ts/pull/331
=> Fix custom parameters not being parsed in complex conditions

packages/shared/package.json, packages/shared/src/contracts/registry.ts, packages/shared/test/registry.spec.ts, packages/taco/package.json, pnpm-lock.yaml
- Bugfix
- 1
- Fixes not using the default import in contract registry import (from `nucypher-contracts` package)
- Fixes linter
- Releases new RC version
> - Fixes #...
- You can see the actual fix [here](https://github.com/nucypher/nucypher-ts/pull/353/files#r1367686471). The remainder of this PR are chores that have to do fix fixing the lining and releasing the fixed RC version.
=> Fix contract registry not parsing contract artifacts correctly

packages/taco/src/conditions/context/context.ts, packages/taco/test/conditions/context.test.ts
=> Fix  `ConditionContext` not detecting falsy parameters

.gitignore, demos/taco-demo/src/ConditionBuilder.tsx, demos/taco-nft-demo/src/NFTConditionBuilder.tsx, examples/taco/nextjs/src/app/page.tsx, examples/taco/nodejs/src/index.ts, examples/taco/react/src/App.tsx, examples/taco/webpack-5/src/index.ts, package.json, packages/taco/.eslintrc.js, packages/taco/README.md, packages/taco/examples/README.md, packages/taco/examples/conditions.ts, packages/taco/examples/context.ts, packages/taco/examples/encrypt-decrypt.ts, packages/taco/package.json, packages/taco/src/conditions/base/contract.ts, packages/taco/src/conditions/base/index.ts, packages/taco/src/conditions/predefined/erc721.ts, packages/taco/test/conditions/base/condition.test.ts, packages/taco/test/conditions/base/contract.test.ts, packages/taco/test/conditions/base/rpc.test.ts, packages/taco/test/conditions/base/time.test.ts, packages/taco/test/conditions/compound-condition.test.ts, packages/taco/test/conditions/condition-expr.test.ts, packages/taco/test/dkg-client.test.ts, packages/taco/test/test-utils.ts, packages/taco/tsconfig.cjs.json, packages/taco/tsconfig.json
- Feature
- 2
- Adds `or` and `and` shorthand methods to `CompoundCondition`
- Removes mandatory `conditionType` from conditions constructors. It's now inferred inside the constructor. The condition props still contain the `conditionType` field to ensure it's validation.
> - Fixes #...
- Based on https://github.com/nucypher/nucypher-ts/pull/365, please review it first
=> Quality of life updates to conditions

.gitignore, package.json, packages/taco/.eslintrc.js, packages/taco/README.md, packages/taco/examples/README.md, packages/taco/examples/conditions.ts, packages/taco/examples/encrypt-decrypt.ts, packages/taco/package.json, packages/taco/src/conditions/predefined/erc721.ts, packages/taco/test/conditions/base/condition.test.ts, packages/taco/test/conditions/compound-condition.test.ts, packages/taco/test/conditions/condition-expr.test.ts, packages/taco/test/dkg-client.test.ts, packages/taco/test/test-utils.ts, packages/taco/tsconfig.cjs.json, packages/taco/tsconfig.json
-  Documentation
- 1
- Fixes chores related to code examples used in Gitbook
- Fixes issues with `typedoc` generated docs on GH Pages
- Fixes some type-checking issues that previously went undetected
- Fixes #300 
- `taco/src/examples` are not run at the moment, but are type-checked (compiled) instead - It should catch any issues with the API, but will not catch bugs in `taco`. For that, we implement tests in `taco/test`
- A preview of generated docs is available here: https://nucypher.github.io/nucypher-ts/
=> Update Gitbook docs

.gitignore, demos/taco-demo/src/ConditionBuilder.tsx, demos/taco-nft-demo/src/NFTConditionBuilder.tsx, examples/taco/nextjs/src/app/page.tsx, examples/taco/nodejs/src/index.ts, examples/taco/react/src/App.tsx, examples/taco/webpack-5/src/index.ts, package.json, packages/taco/.eslintrc.js, packages/taco/README.md, packages/taco/examples/README.md, packages/taco/examples/conditions.ts, packages/taco/examples/context.ts, packages/taco/examples/encrypt-decrypt.ts, packages/taco/package.json, packages/taco/src/conditions/base/contract.ts, packages/taco/src/conditions/base/index.ts, packages/taco/src/conditions/compound-condition.ts, packages/taco/src/conditions/predefined/erc721.ts, packages/taco/test/conditions/base/condition.test.ts, packages/taco/test/conditions/base/contract.test.ts, packages/taco/test/conditions/base/rpc.test.ts, packages/taco/test/conditions/base/time.test.ts, packages/taco/test/conditions/compound-condition.test.ts, packages/taco/test/conditions/condition-expr.test.ts, packages/taco/test/dkg-client.test.ts, packages/taco/test/test-utils.ts, packages/taco/tsconfig.cjs.json, packages/taco/tsconfig.json
- Feature
- 2
- Adds support for `not` operator
- Refines error messages for `CompoundCondition`
- Fixes #369
- Based on https://github.com/nucypher/nucypher-ts/pull/367. Please review it first.
=> Support `not` operator in `CompoundCondition`

packages/shared/package.json, packages/shared/src/contracts/agents/coordinator.ts, packages/taco/src/dkg.ts, packages/taco/src/taco.ts, packages/taco/test/taco.test.ts, packages/taco/test/test-utils.ts, pnpm-lock.yaml
Updates `taco-web` to incorporate latest changes made via https://github.com/nucypher/nucypher-contracts/pull/187.
> - Fixes #...
> What should reviewers focus on?
=> Update DKG states based on last minute changes to Coordinator contract.

packages/taco/test/conditions/base/condition.test.ts, packages/taco/test/conditions/base/contract.test.ts, packages/taco/test/conditions/base/rpc.test.ts, packages/taco/test/conditions/base/time.test.ts, packages/taco/test/conditions/compound-condition.test.ts, packages/taco/test/conditions/context.test.ts
-  Other
- 1
> - Fixes #...
- Based on top of #379 
- Ideas for testing cases welcome
=> Add test cases for conditions

demos/taco-demo/package.json, demos/taco-nft-demo/package.json, examples/pre/nextjs/package.json, examples/pre/nodejs/package.json, examples/pre/react/package.json, examples/pre/webpack-5/package.json, examples/pre/webpack-5/src/index.ts, examples/taco/nextjs/package.json, examples/taco/nodejs/package.json, examples/taco/webpack-5/src/index.ts, package.json, packages/pre/package.json, packages/shared/package.json, packages/shared/scripts/typechain.ts, packages/shared/src/contracts/agents/coordinator.ts, packages/taco/package.json, packages/test-utils/package.json, pnpm-lock.yaml
- Other
- 1
- Fixes #401
> What should reviewers focus on?
=> Update peer & core dependencies config

examples/taco/nodejs/src/index.ts, packages/taco/src/conditions/base/shared.ts, packages/taco/test/conditions/context.test.ts
- Documentation
- 1
Adds a more clear and understandable example code for Taco by separating the encrypt and decrypt functions
It was not clear in the example how to create an encrypted message, send it somewhere else, and decrypt it later. The decryption code parts were using objects from encryption. So I separated encrypt and decrypt functions to show the users how they can be separately used.
=> refactor: taco nodejs example

.github/workflows/tapir.yml, demos/taco-demo/src/config.ts, demos/taco-nft-demo/src/config.ts, examples/taco/nodejs/.env.example, examples/taco/nodejs/src/index.ts, packages/pre/test/acceptance/alice-grants.test.ts, packages/pre/test/acceptance/delay-enact.test.ts, packages/shared/package.json, packages/shared/src/porter.ts, packages/taco/test/taco.test.ts, pnpm-lock.yaml
- Other
- 1
- Adds `.env` based config for `domain` and `ritualId` in the nodejs `taco` example
- Adds a CI job for `tapir` testnet 
- Renames `domain.DEV` to `domain.DEVNET` for consistency
=> Add a `tapir` CI job

demos/taco-nft-demo/src/NFTConditionBuilder.tsx, packages/shared/src/web3.ts, packages/taco/examples/conditions.ts, packages/taco/examples/context.ts, packages/taco/examples/encrypt-decrypt.ts, packages/taco/src/conditions/const.ts, packages/taco/test/conditions/base/condition.test.ts, packages/taco/test/conditions/base/time.test.ts, packages/taco/test/conditions/compound-condition.test.ts, packages/taco/test/conditions/conditions.test.ts, packages/taco/test/taco.test.ts, packages/taco/test/test-utils.ts, packages/test-utils/src/variables.ts, packages/test-utils/tsconfig.json
- Feature
- 1
- Refers to: https://github.com/nucypher/tdec/issues/139
**Why is it needed:**
- Goerli is entering [end-of-life on January 2024](https://ethereum-magicians.org/t/proposal-predictable-ethereum-testnet-lifecycle/11575)
=> Deprecate support for Goerli

.github/workflows/tapir.yml, demos/taco-demo/src/config.ts, demos/taco-nft-demo/src/config.ts, examples/taco/nextjs/src/app/page.tsx, examples/taco/nodejs/.env.example, examples/taco/nodejs/src/index.ts, examples/taco/react/src/App.tsx, examples/taco/webpack-5/src/index.ts, packages/shared/package.json, pnpm-lock.yaml
- Other
- 1
- Updates `tapir` ritual to use id `0`
- Updates contract registry using new `@nucypher/nucypher-contracts:0.16.0` version
- There seems to be some issue with [Infura project settings](https://github.com/nucypher/taco-web/actions/runs/7492767616/job/20397015512?pr=462#step:7:22). It works fine on the `lynx` job, but fails on the `tapir` job. I updated `tapir` job to use a public RPC instead.
=> Update `tapir` ritual

demos/taco-demo/package.json, demos/taco-nft-demo/package.json, examples/taco/nodejs/src/index.ts, package.json, packages/shared/package.json, packages/taco/package.json, pnpm-lock.yaml
- Other
- 1
- One of the underlying dependencies, `@nucypher/nucypher-contracts` was updated
- Necessary to keep `taco-web` working for `tapir` users
=> Release `taco@0.2.x`

packages/taco/src/conditions/predefined/erc20.ts, packages/taco/src/conditions/predefined/index.ts, packages/taco/test/conditions/predefined/erc20.test.ts, packages/taco/test/conditions/predefined/erc721.test.ts
- Feature
- 1
- I think we already had this one at some point, but it must have been accidentally removed
- Also adds tests for `ERC721` predefined conditions
=> Add predefined `ERC20BalanceOf` condition

.github/workflows/lynx.yml, examples/taco/nodejs/src/index.ts, packages/shared/package.json, packages/shared/src/web3.ts, packages/taco/src/conditions/const.ts, packages/taco/test/conditions/base/condition.test.ts, packages/taco/test/conditions/conditions.test.ts, pnpm-lock.yaml
- Feature
- 1
- Adds support for Amoy, chain id 80002
- Updates `taco-web` to use `nucypher-contracts@0.21.0`
- Mumbai is to be deprecated
- Related issue: #506 
- Related issue: https://github.com/nucypher/nucypher-contracts/pull/250
=> Update `lynx` to use Polygon Amoy testnet

.github/workflows/npm.yml
- Other
- 1
- Checks whether `@nucypher/taco` has a correct build available under expected npm tags
- To catch bad builds and tagging issues
=> Test npm package availability on CI

demos/taco-demo/README.md, demos/taco-demo/package.json, demos/taco-demo/src/App.tsx, demos/taco-demo/src/ConditionBuilder.tsx, demos/taco-demo/src/Decrypt.tsx, demos/taco-demo/src/Encrypt.tsx, demos/taco-demo/src/config.ts, demos/taco-demo/src/irys.ts, demos/taco-demo/tsconfig.json, demos/taco-demo/webpack.config.js, pnpm-lock.yaml
- Other
- 1
- Stores message encrypted during `taco-demo` on a free Irys node
- Do we want to add integration examples with third parties to the repo? Should we contact them first? Does this count as an endorsement?
- Should we document this further in our GitBook docs?
- Should we create a separate demo for Irys rather than modifying the existing `taco-demo`?
- Merging blocked because Irys depends on Mumbai - To be resolved before merging
=> Add Irys Arweave bundler usage to `taco-demo`

packages/taco/src/conditions/base/contract.ts
This change will add the solidity type `address payable` to the list of types that are supported by schema validation.
When using a contract-type condition with `address payable` as the internal type, an error is raised.
For instance, the following function ABI
```solidity
const funcABI: conditions.base.contract.FunctionAbiProps = {
inputs: [
{
internalType: 'bytes32',
name: 'node',
type: 'bytes32',
},
],
name: 'addr',
outputs: [
{
internalType: 'address payable', // <- Problem here
name: '',
type: 'address',
},
],
stateMutability: 'view',
type: 'function',
};
```
will return the following error:
```
/Users/manumonti/Projects/nucypher/taco-web/packages/taco/src/conditions/condition.ts:19
throw new …
```
=> Add "address payable" to schema validation

demos/taco-demo/src/App.tsx, demos/taco-nft-demo/src/App.tsx
- Documentation
We've had a couple of messages at hackathons where people ask to have their wallet added to allow list. This is no longer required because ritual id 0 is fully open
=> Remove instruction to add wallet to allow list

.github/workflows/lynx.yml, .github/workflows/main.yml, .github/workflows/mainnet.yml, .github/workflows/npm.yml, .github/workflows/release.yml, .github/workflows/tapir.yml, demos/taco-demo/src/irys.ts, package.json, packages/shared/package.json, packages/taco/package.json, pnpm-lock.yaml
- Bugfix
- 1
- Fixes `taco-web` not working on Node.js 18+ versions
- Takes advantage of recently released `@nucypher/nucypher-core@0.14.5` that contains an actual fix
- This change has been tested with Node.js [18, 20, 22] versions locally and [on CI](https://github.com/piotr-roslaniec/nucypher-ts/blob/dd26e538d77953bee03723ec47a6463d26221831/.github/workflows/main.yml#L12-L12)
- Related: https://github.com/nucypher/taco-web/issues/513
=> Fix `taco-web` support for the LTS versions of NodeJs

packages/taco-auth/src/providers/eip712.ts, packages/taco-auth/src/types.ts
- Feature
- 1
- Marks `EIP712AuthProvider` as deprecated
- Refers to https://github.com/nucypher/tdec/issues/178
- Should we outright remove EIP712 support instead of deprecating it? If not, what is a good timeline to allow `taco-web` users to adjust?
- Created https://github.com/nucypher/taco-web/issues/536
=> Deprecate EIP712 authentication provider

packages/shared/package.json, packages/shared/src/index.ts, packages/shared/src/schemas.ts, packages/shared/test/schemas.test.ts, packages/taco-auth/package.json, packages/taco-auth/src/auth-provider.ts, packages/taco-auth/src/auth-sig.ts, packages/taco-auth/src/helper.ts, packages/taco-auth/src/index.ts, packages/taco-auth/src/providers/eip4361.ts, packages/taco-auth/src/providers/eip712.ts, packages/taco-auth/src/providers/index.ts, packages/taco-auth/src/storage.ts, packages/taco-auth/test/auth-provider.test.ts, packages/taco-auth/test/auth-sig.test.ts, packages/taco/package.json, packages/taco/src/conditions/base/contract.ts, packages/taco/src/conditions/const.ts, packages/taco/src/conditions/shared.ts, packages/taco/test/conditions/base/rpc.test.ts, packages/taco/test/conditions/context.test.ts, packages/test-utils/package.json, packages/test-utils/src/utils.ts, pnpm-lock.yaml
- Feature
- 2
- Implements `AuthSignature` validation with `zod`
- Moves some code around in `taco-auth` to prevent circular-dependency issues that break `zod`
- Fixes https://github.com/nucypher/taco-web/issues/535
- ...
=> Validate user-provided `AuthSignature`

package.json
- Other
- 1
- Always points to `nucypher/taco-web` as a destination for `typedoc` docs publishing
=> Set repo URL in `typedoc:publish` command

examples/taco/nodejs/src/index.ts, packages/shared/src/index.ts, packages/shared/src/schemas.ts, packages/shared/test/schemas.test.ts, packages/taco-auth/src/auth-sig.ts, packages/taco-auth/src/index.ts, packages/taco-auth/src/providers/eip4361.ts, packages/taco-auth/src/providers/external-eip4361.ts, packages/taco-auth/src/providers/index.ts, packages/taco-auth/test/auth-provider.test.ts, packages/taco-auth/test/auth-sig.test.ts, packages/taco/examples/conditions.ts, packages/taco/examples/encrypt-decrypt.ts, packages/taco/src/conditions/condition-expr.ts, packages/taco/src/conditions/const.ts, packages/taco/src/conditions/context/context.ts, packages/taco/src/conditions/predefined/erc20.ts, packages/taco/src/conditions/predefined/erc721.ts, packages/taco/src/conditions/shared.ts, packages/taco/src/taco.ts, packages/taco/src/tdec.ts, packages/taco/src/types.ts, packages/taco/test/conditions/base/contract.test.ts, packages/taco/test/conditions/condition-expr.test.ts, packages/taco/test/conditions/context.test.ts, packages/taco/test/conditions/predefined/erc721.test.ts, packages/taco/test/taco.test.ts, packages/taco/test/test-utils.ts, packages/test-utils/src/utils.ts
Add support to reuse SIWE messages on taco-web from other applications.
> - Fixes #...
Related to https://github.com/nucypher/sprints/issues/22
Based on #546 .
=> Reuse siwe authentication

packages/taco/src/conditions/base/json-api.ts, packages/taco/src/conditions/condition-factory.ts, packages/taco/test/conditions/base/json.test.ts, packages/taco/test/conditions/condition-expr.test.ts, packages/taco/test/test-utils.ts
Fixes https://github.com/nucypher/sprints/issues/23
=> Add JsonApiCondition

packages/taco/package.json, packages/taco/src/conditions/base/json-api.ts, packages/taco/test/conditions/base/json-api.test.ts, packages/taco/test/conditions/base/json.test.ts, packages/taco/test/conditions/condition-expr.test.ts, packages/taco/test/test-utils.ts, pnpm-lock.yaml
> Added JSONPath syntactic validation
Related to https://github.com/nucypher/taco-web/pull/550/files#r1696888086
> - Fixes #559 
This depends on the PR #550
With the integrated PR #550 my approach is to use it in the following way
```
export const JsonApiConditionSchema = z.object({
conditionType: z.literal(JsonApiConditionType).default(JsonApiConditionType),
endpoint: z.string().url(),
parameters: z.record(z.string(), z.unknown()).optional(),
query: jsonPathSchema.optional(),
returnValueTest: …
```
=> Added JSONPath syntactic validation

demos/taco-demo/src/App.tsx, demos/taco-nft-demo/src/App.tsx, examples/taco/nextjs/src/hooks/useTaco.ts, examples/taco/nodejs/src/index.ts, examples/taco/react/src/hooks/useTaco.ts, examples/taco/webpack-5/src/index.ts, packages/shared/package.json, packages/shared/src/porter.ts, packages/shared/test/porter.test.ts, packages/shared/tsconfig.json, packages/taco/examples/encrypt-decrypt.ts, packages/taco/src/index.ts, packages/taco/src/taco.ts, packages/taco/src/tdec.ts, packages/taco/test/taco.test.ts, packages/test-utils/src/utils.ts, pnpm-lock.yaml
=> Multiple Porter URIs

examples/pre/nextjs/src/app/page.tsx, examples/pre/nodejs/src/index.ts, examples/pre/react/src/App.tsx, examples/pre/webpack-5/src/index.ts, examples/taco/webpack-5/src/index.ts, packages/shared/src/porter.ts, packages/shared/test/porter.test.ts, packages/taco/README.md, packages/taco/src/taco.ts
=> GitHub Porter URIs

examples/taco/nextjs/src/hooks/useTaco.ts, examples/taco/nodejs/src/index.ts, examples/taco/react/src/hooks/useTaco.ts, examples/taco/webpack-5/src/index.ts, packages/shared/src/porter.ts, packages/shared/test/porter.test.ts, packages/taco-auth/src/auth-provider.ts, packages/taco-auth/src/auth-sig.ts, packages/taco-auth/src/providers/eip4361/common.ts, packages/taco-auth/src/providers/eip4361/eip4361.ts, packages/taco-auth/src/providers/eip4361/external-eip4361.ts, packages/taco-auth/src/providers/external-eip4361.ts, packages/taco-auth/src/providers/index.ts, packages/taco-auth/test/auth-provider.test.ts, packages/taco/examples/encrypt-decrypt.ts, packages/taco/src/conditions/condition-expr.ts, packages/taco/src/conditions/const.ts, packages/taco/src/conditions/context/context.ts, packages/taco/src/conditions/shared.ts, packages/taco/src/index.ts, packages/taco/src/taco.ts, packages/taco/src/tdec.ts, packages/taco/test/conditions/base/contract.test.ts, packages/taco/test/conditions/conditions.test.ts, packages/taco/test/conditions/context.test.ts, packages/taco/test/taco.test.ts, packages/test-utils/src/utils.ts
- Rework of decryption API to use `ConditionContext` instead of splitting up params for authProvider and customParameters.
- Allow `ConditionContext` to be populated by developers with authProviders and customParameters before being used for decryption
- Reduce parameters used in calls for decryption -> retrieve flow. Instead only obtain the ritual from the ritual id when the values are actually needed.
The updated use of the code will look like the following:
1. Create condition context from message kit:
```typescript
const conditionContext = conditions.context.ConditionContext.fromMessageKit(messageKit);
```
2. Add any required auth provider(s):
* Add auth provider for `:userAddress`, if necessary:
```typescript
const …
```
=> Decrypt API Rework

demos/taco-demo/README.md, demos/taco-demo/package.json, demos/taco-demo/src/App.tsx, demos/taco-nft-demo/README.md, demos/taco-nft-demo/package.json, demos/taco-nft-demo/src/App.tsx, pnpm-lock.yaml
Update `taco-web` demos to use latest released versions of `@nucypher/taco` and `@nucypher/taco-auth`.
- Related to https://github.com/nucypher/taco-web/issues/566
- Closes https://github.com/nucypher/sprints/issues/57
=> Update `taco-web` demos to use latest released version of `taco`, `taco-auth`

CONTRIBUTING.md
Document steps around publishing to npm.
> - Fixes #...
=> Document steps for publishing packages to npm

.github/workflows/lynx.yml
This change will change the ritual ID used by the test performed every hour on the Lynx network. This is needed because the Lynx ritual `#0` has expired, so a new ritual has been initiated (`#27`).
This PR has been opened through a branch on the repo (`update-ritual-id`) instead of a branch on my fork since I needed to test the change before opening this PR.
=> Update Ritual ID on test lynx workflow

packages/taco/src/conditions/base/rpc.ts, packages/taco/src/conditions/compound-condition.ts, packages/taco/src/conditions/condition.ts, packages/taco/src/conditions/index.ts, packages/taco/src/conditions/multi-condition.ts, packages/taco/src/conditions/sequential.ts, packages/taco/test/conditions/compound-condition.test.ts, packages/taco/test/conditions/sequential.test.ts, packages/taco/test/test-utils.ts
Merge already existing `epic-sequential-condition` work into this epic for next version of `taco`. The PRs into the original epic were already reviewed, so no need to review them here - just wait CI to complete successfully.
> - Fixes #...
=> Merge `epic-sequential-condition`

.github/workflows/tapir.yml, demos/taco-demo/src/config.ts, demos/taco-nft-demo/src/config.ts, examples/taco/nextjs/src/app/page.tsx, examples/taco/nodejs/.env.example, examples/taco/nodejs/src/index.ts, examples/taco/react/src/App.tsx, examples/taco/webpack-5/src/index.ts
The open ritual that we used for developers has expired on Oct 6th 24, so a new ritual `#6` has been created for this.
Failing tests should pass when this change is merged.
epic-v0.6.x branch should rebase this change once merged.
=> chore: update ritual used by Tapir action

packages/taco/src/conditions/base/contract.ts, packages/taco/test/conditions/base/contract.test.ts
> Added Human-Readable ABI format
> - Fixes https://github.com/nucypher/taco-web/issues/370
=> Added Human-Readable ABI format

.github/workflows/mainnet.yml
The previous ritual has expired, so a new ritual has been generated to check that mainnet TACo domain is up and running.
The PR was created over a branch on this repo instead of my fork because AFAIK having a branch here is the easiest way to trigger the CI tests.
=> Update ritual ID used in mainnet checks

packages/taco/src/conditions/condition-factory.ts, packages/taco/src/conditions/if-then-else-condition.ts, packages/taco/src/conditions/index.ts, packages/taco/src/conditions/multi-condition.ts, packages/taco/src/conditions/schemas/if-then-else.ts, packages/taco/src/conditions/schemas/utils.ts, packages/taco/test/conditions/if-then-else-condition.test.ts, packages/taco/test/conditions/lingo.test.ts
Based over #591 .
Initial implementation of `IfThenElseCondition`.
Related to https://github.com/nucypher/nucypher/pull/3558.
> - Fixes #...
=> feat:  implementation of `IfThenElseCondition`

packages/shared/src/schemas.ts, packages/shared/test/schemas.test.ts, packages/taco/src/conditions/schemas/common.ts, packages/taco/src/conditions/schemas/contract.ts, packages/taco/src/conditions/schemas/rpc.ts, packages/taco/test/conditions/base/condition.test.ts, packages/taco/test/conditions/base/contract.test.ts, packages/taco/test/conditions/base/rpc.test.ts
=> Improved schema validation for eth_getBalance

packages/shared/src/schemas.ts, packages/shared/test/schemas.test.ts, packages/taco/src/conditions/const.ts, packages/taco/src/conditions/context/context.ts, packages/taco/src/conditions/schemas/context.ts, packages/taco/src/conditions/schemas/json-api.ts, packages/taco/src/conditions/schemas/rpc.ts, packages/taco/test/conditions/base/json.test.ts, packages/taco/test/conditions/base/rpc.test.ts
Based over #598 .
Updates the `taco-web` code to allow `authorizationToken` to be optionally provided for OAuth/JWT support.
- Closes https://github.com/nucypher/sprints/issues/85.
- Related to https://github.com/nucypher/nucypher/pull/3560
=> feat: allow authorization token for `JsonApiCondition` to support endpoints requiring OAuth, JWT authorization

packages/taco/src/conditions/context/context.ts, packages/taco/test/taco.test.ts
Context params where not being parsed from endpoint, query, or authToken. This PR fixes those issues and adds a test
=> Fix JSON API conditions

packages/taco/src/conditions/context/context.ts, packages/taco/test/taco.test.ts
There were recommended changes from a review of #602 after it was merged. This PR applies those changes.
See:
- https://github.com/nucypher/taco-web/pull/602#discussion_r1832643945
- https://github.com/nucypher/taco-web/pull/602#discussion_r1832651228
> - Fixes #...
> of your PR that requires more attention …
=> Apply outstanding RFCs from #602

packages/taco-auth/src/providers/eip4361/eip4361.ts, packages/taco-auth/test/auth-provider.test.ts
There isn't anything from a programmatic/non-browser based scenario that prevents us from using default hardcoded values if:
1) specific values aren't provided by application
AND
2) we are not in a browser-based environment.
Therefore, you could do something like, if the above scenarios hold then we use `https://taco.build` and `taco.build` as the defaults (of course we can use something else) for uri and domain respectively. 
In a programmatic environment, it shouldn't really care the domain/URI value, just that the wallet signed something. Even more broadly, the `domain` and `uri` values are really for UI elements to show the user that the connected site is indeed prompting for SIWE. Furthermore, TACo nodes don't verify anything …
=> Use default hardcoded values for `domain` and `uri` within the EIP4361 message in non-browser environment

packages/taco/package.json, packages/taco/schema-docs/condition-schemas.md, packages/taco/src/conditions/base/index.ts, packages/taco/src/conditions/base/jwt.ts, packages/taco/src/conditions/condition-factory.ts, packages/taco/src/conditions/schemas/export-for-zod-doc-gen.ts, packages/taco/src/conditions/schemas/jwt.ts, packages/taco/src/conditions/schemas/utils.ts, packages/taco/test/conditions/base/jwt.test.ts, packages/taco/test/conditions/compound-condition.test.ts, packages/taco/test/conditions/lingo.test.ts, packages/taco/test/test-utils.ts, packages/test-utils/src/variables.ts, pnpm-lock.yaml
Implements JWT condition
See [#3567](https://github.com/nucypher/nucypher/issues/3567)
=> JWT condition
